# Generated by Django 4.2.3 on 2023-08-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_desktop', models.ImageField(upload_to='')),
                ('image_mobile', models.ImageField(upload_to='')),
                ('link', models.URLField(verbose_name='Link')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
